### ISSUE TITLE
Implementovať pridávanie ciest adminom

### ISSUE THREAD

**Issue by silviabielikova** [TIS2023-FMFI/pracovne-cesty#106]
Myšlienka je taká, že by url create viewu vyzerala v tom prípade napr. takto: http://localhost:8000/trips/create?user=1, do create sa pošle aj user z databázy, doplnia sa o ňom vo frontende údaje. Store url potom podobne môže fungovať takto: http://localhost:8000/trips?user=1, cesta sa uloži pre usera 1.

Ak máte lepší nápad, určite píšte.

**Comment by Mcibula** [comment]
Ja by som tu mozno navrhol, aby ludia v tom lavom paneli, co ma admin v dashboarde mali pri sebe jednoduche tlacidlo `+`, ktore umozni adminovi pridat cestu za daneho usera. Na backende to moze potom fungovat s tymi urls, ako si napisala.
