### ISSUE TITLE
Doplňujúce otázky pre zadávateľku

### ISSUE THREAD

**Issue by Mcibula** [TIS2023-FMFI/pracovne-cesty#13]
1. Mať čas prekročenia hraníc už pri vytváraní cesty?
2. Vypýtať si údaje k ŠPP prvkom.
3. Potrebujeme zobrazovať typ cestujúceho slovom?

**Comment by silviabielikova** [comment]
1. Čas prekročenia hraníc stačí až pri správe
2. Údaje k ŠPP prvkom ešte nie sú pripravené, ale dostaneme ich. Vieme však, ako bude vyzerať tabuľka v databáze, lebo poznáme stĺpce (fond, FO, fin.stredisko, ŠPP prvok, rozpočtová položka, zdopovedný riešiteľ - tak, ako je to v dohode)
3. Nie, nepotrebujeme
