### ISSUE TITLE
oprava, vymazanie

### ISSUE THREAD

**Issue by andylucny** [TIS2023-FMFI/pracovne-cesty#135]
zadanu pracovnu cestu nemozno ani vymazit ani opravit

ja som sice zadal zly mesiac (vymazte to prosim) ale aj ked je vestko dobre, cas prichodu a odchodu sa dopredu nevie a treba ho dodatocne upravit

**Comment by Mcibula** [comment]
Dobrý deň, áno, niektoré údaje, vrátane času príchodu a odchodu, sa dajú upraviť po návrate z cesty pri dodávaní správy o ceste.

**Comment by pavelpetrovic** [comment]
Upravil som apríl na máj. Ak chceš aj tak cestu zmazať, skús tam stlačiť Storno, malo by to nejak Zdenke vyskočiť, že je na zmazanie. Ale ak to tam necháš takto, tak sa asi poteší, že má na čom testovať systém.
