### ISSUE TITLE
kde sú zdroje PDF templejtov?

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/pracovne-cesty#145]
@Mcibula @silviabielikova @samoslavik45 @ihorbaltsat 

Rýchla otázka: 

Ako ste, prosím, vytvárali PDF templates? Robili ste to vo worde, alebo v niecom inom?
Máte niekde tie pôvodné súbory, z ktorých sa to exportovalo do PDF?
Alebo ste vyrábali v nejakom nástroji rovno PDF formuláre? 
Neviem o tom nájsť žiadnu zmienku v technickej dokumentácii ani na githube, môžete, 
to, prosím, nahrať na github? alebo dať linku na nástroj, ktorý ste použili?

**Comment by Mcibula** [comment]
Dobrý deň,

PDF templaty sa podľa sekcie II.5 Technickej dokumentácie nachádzaju v [src/storage/app/pdf_templates](https://github.com/TIS2023-FMFI/pracovne-cesty/tree/main/src/storage/app/pdf_templates). Tieto templaty sa vyrábali cez online PDF form creator, je ich celkom dosť, jeden je napríklad [DocFly](https://www.docfly.com/pdf-form-creator), s ktorým sme začínali, ale už si nepamätám, ktorý sme potom používali. Originálne dokumenty boli len v PDF stiahnuté z [https://zona.fmph.uniba.sk/sluzby-a-administrativa/tlaciva/](https://zona.fmph.uniba.sk/sluzby-a-administrativa/tlaciva/) a anotované potom cez ten nástroj. Na tej stránke sú niektoré aj v docx, ale nie všetky.

**Comment by pavelpetrovic** [comment]
vďaka za reakciu @Mcibula, presne tie templejty som mal na mysli.
ale keď to natiahnem do toho DocFly, tak tam nevidim tie identifikatory poli formulara.
vidim tam v arrange fields - form field order - len nejake "xy-undefined".
mozno ste teda pouzivali iny nastroj, alebo ked sa clovek zaregistruje v DocFly, tak tam uvidi viac?

**Comment by pavelpetrovic** [comment]
zistil som, ze nazvy poli si viem vypisat cez 

pdftk templejt.pdf dump_data_fields

takze som doplnil to chybajuce miesto pre tuzemsku cestu,
ale bude treba robit dalsie upravy v PDF templejtoch a preto musim zistit ako ich mozeme editovat. :-)

**Comment by Mcibula** [comment]
Mne sa podarilo zobrazit si tie nazvy fieldov pomocou tejto [odpovede](https://stackoverflow.com/a/76363813/8488774) na SO, ktora odkazuje na nastroj pdfFiller. Pomocou neho sa da ten form aj upravovat.

**Comment by pavelpetrovic** [comment]
nazvy fieldov ano, aj ich dokonca mozem zmenit, ale downloadnut zmenene asi iba po zadani udajov kreditky cez 30-dnovy trial, ak by bola aj ina moznost, radsej by som pouzil taku.
nikto si nepamatate ako ste tie PDF templejty vytvarali, alebo ste pouzili nejaky komercny tool, ktory isiel nahodou okolo Vas?
