### ISSUE TITLE
Spýtať sa p. Kľuku na posielanie mailov z KAI serveru

### ISSUE THREAD

**Issue by Mcibula** [TIS2023-FMFI/pracovne-cesty#15]

**Comment by silviabielikova** [comment]
Dobry den, Silvia.

Zistil som, ze s odosielanim je skutocne problem, ale je to konfiguracny problem servera, nie principialny problem s pouzitim funkcie mail(). Momentalne to ma fungovat takto:
1. Funkcia mail() odovzda mail na dorucenie mailovemu softveru (postfix) na serveri, kde Pritomnost bezi.
2. Mailovy softver na serveri Pritomnosti preposle mail na katedrovy server.
3. Katedrovy server posle mail adresatovi.
Chyba teraz zrejme nastava v 2. kroku a ide o konfiguracny problem. Nezda sa mi ale ako uplne dobry napad obchadzat problem tym, ze implementujete nejaky iny mechanizmus na odosielanie. Treba to spravne nakonfigurovat (co samozrejme nie je vasa starost).

Na druhej strane: Viem si predstavit, ze keby ste pouzili kniznicu, ktorou odovzdate mail na dorucenie priamo katedrovemu serveru, bolo by to lepsie riesenie. Dalo by sa pouzit aj v situaciach, ked na serveri prevadzkujucom vasu aplikaciu dorucovanie mailov vobec nie je nakonfigurovane (napr. ak by bezala izolovana v kontajneri a pod.). To je dobry dovod spravit to inak a suhlasil by som.

JKľ~


Dobry den este raz.

Trocha som si o tom cital a nie je to konfiguracny problem – mail() je naozaj trocha prilis hlupa funkcia na posielanie mailov s diakritikou. Preto to v Pritomnosti nefunguje:
https://www.php.net/manual/en/function.mail.php#124291
V dokumentacii su odporucane baliky PEAR::Mail a PEAR::Mail_Mime, ktore mozu byt lepsim riesenim (ale treba to overit). Ten prvy umoznuje posielat maily priamo cez odosielaci server (v nasom pripade katedrovy) a druhy by mal zase vediet zostavit maily s komplikovanym obsahom (HTML, diakritika, pripadne obrazky/prilohy).

JKľ~
